### ISSUE TITLE
Use Memory Manager to allocate physical memory < 1MB

### ISSUE THREAD

**Issue by chges100** [hhuOS/hhuOS#24]
Use some allocation algorithm (e.g. buddy) to manage physical memory < 1MB for real mode or DMA. The gap between 0x500 up to 0x80000 provides suitable memory for this.

**Comment by fruhland** [comment]
This issue has been addressed by a7da282. However, the current solution is using a FreeListMemoryManager to manage the lower memory, which is not optimal, since we mostly need aligned chunks of memory, which leads to a lot of wasted space using this manager. A manager based on the buddy algorithm would probably be more suitable.
